config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  resources :about, only: [:index]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, except: [:edit, :update, :show, :destroy]
    resources :sales , only: [:index, :new]
  end

end

app/views/layouts/_top_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Jungle</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Home', :root %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Categories
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <% Category.all.each do |category| %>
              <li><%= link_to category.name, category %></li>
            <% end %>
          </ul>
        </li>
        <li>
         <%= link_to "About Us", [:about, :index] %>      
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      <li>  
        <div class="user_links">
          <% if current_user %>
          Signed in as <%= current_user.first_name %> | <%= link_to "Logout", '/logout' %>
          <% else %>
          <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
          <% end %>
        </div>  
      </li>
       
       <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">

            <span class="text-danger"><%= fa_icon 'lock', text: 'Admin' %></span>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Dashboard', [:admin, :root] %></li>
            <li><%= link_to 'Products',  [:admin, :products] %></li>
            <li><%= link_to 'Categories',  [:admin, :categories] %></li>
          </ul>
        </li>
        <li>
          <%= link_to cart_path do %>
            <%= fa_icon "shopping-cart" %> My Cart (<%= cart.size %>)
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jungle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/top_nav' %>
  
  <main class="container">
    <% if active_sale? %>
      <p class="alert alert-info"> 
        Tere's an active Back to school sale going on!
      <strong> Everything is <%= 15 %>% off!</strong>
      </p>
    <% end %>
    <%= yield %>
  </main>

  <%= yield :end_of_body %>
</body>
</html>